version: '2'
services:
    project_betha-app:
        image: project_betha
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://project_betha-mysql:3306/project_betha?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=project_betha-elasticsearch:9300
        ports:
            - 8080:8080
    project_betha-mysql:
        extends:
            file: mysql.yml
            service: project_betha-mysql
    project_betha-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: project_betha-elasticsearch
